services:
  - type: web
    name: job-bidding-platform
    env: node
    buildCommand: cd client && npm install && cd ../server && npm install
    startCommand: cd client && npm run dev & cd ../server && npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        value: "http://localhost:3000"
    healthCheckPath: /api/health